# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'builditdummy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for builditdummy
  pod 'MobileCenter/Crashes', '~> 0.14.1'
  pod 'MobileCenter/Analytics', '~> 0.14.1'
  pod 'RNMobileCenterShared', '~> 0.11.2'

  

  target 'builditdummyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'builditdummy-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for builditdummy-tvOS

  target 'builditdummy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
